name: Run Cypress Tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      # Step to check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step to set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step to install dependencies
      - name: Install dependencies
        run: npm install

      # Step to run Cypress tests on different browsers
      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }}

      # Step to generate Allure report
      - name: Generate Allure report
        run: |
          npx allure generate allure-results --clean -o allure-report

      # Step to upload Allure report as an artifact
      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report