name: Cypress Tests

on: push

jobs:
  ## Run Cypress tests
  cypress-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        browser: [chrome, firefox, edge, safari]
        include:
          - os: macos-latest
            browser: safari
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}  # 'chrome', 'firefox', 'edge', 'electron', 'safari'
          headless: true

  ## Add allure report job into github pages, it will run after each cypress-run job

  allure-report:
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Allure report artifact
        uses: actions/download-artifact@v3
        with:
          name: allure-report
