name: Cypress Tests

on: push

jobs:
  ## Run Cypress tests
  cypress-run-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          browser: chrome
  cypress-run-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
  cypress-run-edge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: edge
  cypress-run-safari:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: safari
  ## Add allure report job into github pages, it will run after each cypress-run job

  allure-report:
    runs-on: ubuntu-latest
    needs: [cypress-run-chrome, cypress-run-firefox, cypress-run-edge, cypress-run-safari]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Allure report artifact
        uses: actions/download-artifact@v3
        with:
          name: allure-report
