name: Cypress Tests

on: push

jobs:
  ## Run Cypress tests
  cypress-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}  # 'chrome', 'firefox', 'edge', 'electron', 'safari'
          headless: true

  ## For each execution of cypress-run job it should upload the report into github pages

  allure-report:
    runs-on: ubuntu-latest
    if: always()
    needs: cypress-run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Allure report artifact
        uses: actions/download-artifact@v3
        with:
          name: allure-report

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Allure commandline
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Serve Allure report
        run: |
          allure serve allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
